//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciclos : IEquatable<Ciclos>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ciclos()
        {
            this.Alumnos = new HashSet<Alumnos>();
            this.OfertasFCT = new HashSet<OfertasFCT>();
        }

        public Ciclos(string id)
        {
            Id = id;
        }

        public Ciclos(string id, string nombre) : this(id)
        {
            Nombre = nombre;
        }

        public Ciclos(string id, string nombre, string tipo) : this(id, nombre)
        {
            Tipo = tipo;
        }

        public Ciclos(string id, string nombre, string tipo, ICollection<Alumnos> alumnos) : this(id, nombre, tipo)
        {
            Alumnos = alumnos;
        }

        public Ciclos(string id, string nombre, string tipo, ICollection<Alumnos> alumnos, ICollection<OfertasFCT> ofertasFCT) : this(id, nombre, tipo, alumnos)
        {
            OfertasFCT = ofertasFCT;
        }

        public string Id { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumnos> Alumnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfertasFCT> OfertasFCT { get; set; }

        public override bool Equals(object obj)
        {
            return Equals(obj as Ciclos);
        }

        public bool Equals(Ciclos other)
        {
            return other != null &&
                   Id.ToUpper() == other.Id.ToUpper();
        }
    }
}
